### ISSUE TITLE
error: no such subcommand: `script`

### ISSUE THREAD

**Issue by losingkeys** [zweifisch/ob-rust#1]
I see the above error with this orgmode file:
```org
* rust
  #+BEGIN_SRC rust
    1 + 4
  #+END_SRC

  #+RESULTS:
```
Do I need the external command `script`? I get the same error after installing that and restarting Emacs.

**Comment by losingkeys** [comment]
Version info:

- **Org mode**: Org mode version 9.1.9 (9.1.9-14-g1a1e47-elpaplus @ /home/me/.emacs.d/elpa/org-plus-contrib-20180416/)
- **Emacs**: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-02-08
- **Linux**: Linux hostname 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 x86_64 GNU/Linux

**Comment by pismute** [comment]
Hi there,
Please check the other project, https://github.com/micanzhang/ob-rust.
Maybe you need to install cargo-script.

**Comment by losingkeys** [comment]
That works! You could probably close this. Maybe there's a way to make that error more readable though? At any rate hopefully people with the same problem will see this issue :)

**Comment by zweifisch** [comment]
@losingkeys the package you are using has nothing to do with this repo.
